runtime: python311

env_variables:
  CLIENT_ID: "${CLIENT_ID}"
  CLIENT_SECRET: "${CLIENT_SECRET}"
  DOMAIN: "${DOMAIN}"
  GCLOUD_STORAGE_BUCKET: "${GCLOUD_STORAGE_BUCKET}"

handlers:
- url: /.*
  script: auto

