runtime: python311

env_variables:
  CLIENT_ID: "${CLIENT_ID}"
  CLIENT_SECRET: "${CLIENT_SECRET}"
  DOMAIN: "${DOMAIN}"
  GCLOUD_STORAGE_BUCKET: "${GCLOUD_STORAGE_BUCKET}"
  APP.SECRET_KEY: "${FLASK_SECRET_KEY}"

handlers:
- url: /.*
  script: auto

